# Generated by Django 4.2.20 on 2025-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://imgs.search.brave.com/v36PCp-pIlb_intMyKbdO378ka5ET7s0aknZFGohom0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9kM2gx/bGcza3N3Nmk2Yi5j/bG91ZGZyb250Lm5l/dC9tZWRpYS9pbWFn/ZS8yMDE4LzA2LzE0/L2M3YmMwYWYzZmNk/YTQ4ZTQ5NzRjYWJm/NGQyZTAxNjA4X0FT/UF9MYW5nb3VzdGlu/ZUF1TWllbChjKUpl/YW5NaWNoZWxEZWxN/b3JhbC5qcGc')),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
